export const users = [
  {
    id: 1,
    firstName: 'Terry',
    lastName: 'Medhurst',
    image: 'https://robohash.org/hicveldicta.png',
  },
  {
    id: 2,
    firstName: 'Sheldon',
    lastName: 'Quigley',
    image: 'https://robohash.org/doloremquesintcorrupti.png',
  },
  {
    id: 3,
    firstName: 'Terrill',
    lastName: 'Hills',
    image: 'https://robohash.org/consequunturautconsequatur.png',
  },
  {
    id: 4,
    firstName: 'Miles',
    lastName: 'Cummerata',
    image: 'https://robohash.org/facilisdignissimosdolore.png',
  },
  {
    id: 5,
    firstName: 'Mavis',
    lastName: 'Schultz',
    image: 'https://robohash.org/adverovelit.png',
  },
  {
    id: 6,
    firstName: 'Alison',
    lastName: 'Reichert',
    image: 'https://robohash.org/laboriosamfacilisrem.png',
  },
  {
    id: 7,
    firstName: 'Oleta',
    lastName: 'Abbott',
    image: 'https://robohash.org/cupiditatererumquos.png',
  },
  {
    id: 8,
    firstName: 'Ewell',
    lastName: 'Mueller',
    image: 'https://robohash.org/quiaharumsapiente.png',
  },
  {
    id: 9,
    firstName: 'Demetrius',
    lastName: 'Corkery',
    image: 'https://robohash.org/excepturiiuremolestiae.png',
  },
  {
    id: 10,
    firstName: 'Eleanora',
    lastName: 'Price',
    image: 'https://robohash.org/aliquamcumqueiure.png',
  },
  {
    id: 11,
    firstName: 'Marcel',
    lastName: 'Jones',
    image: 'https://robohash.org/impeditautest.png',
  },
  {
    id: 12,
    firstName: 'Assunta',
    lastName: 'Rath',
    image: 'https://robohash.org/namquaerataut.png',
  },
];

export const posts = [
  {
    id: 10,
    title: 'They rushed out the door.',
    body: "They rushed out the door, grabbing anything and everything they could think of they might need. There was no time to double-check to make sure they weren't leaving something important behind. Everything was thrown into the car and they sped off. Thirty minutes later they were safe and that was when it dawned on them that they had forgotten the most important thing of all.",
    userId: 1,
  },
  {
    id: 14,
    title: 'The paper was blank.',
    body: "The paper was blank. It shouldn't have been. There should have been writing on the paper, at least a paragraph if not more. The fact that the writing wasn't there was frustrating. Actually, it was even more than frustrating. It was downright distressing.",
    userId: 1,
  },
  {
    id: 95,
    title: 'So what is the answer? How can you stand',
    body: 'From the moment you go to prison you must put your cozy past firmly behind you. At the very threshold, you must say to yourself: “My life is over, a little early to be sure, but there’s nothing to be done about it. I shall never return to freedom.',
    userId: 1,
  },
  {
    id: 23,
    title: "It's an unfortunate reality that we don't teach people how to make money",
    body: "It's an unfortunate reality that we don't teach people how to make money (beyond getting a 9 to 5 job) as part of our education system. The truth is there are a lot of different, legitimate ways to make money. That doesn't mean they are easy and that you won't have to work hard to succeed, but it does mean that if you're willing to open your mind a bit you don't have to be stuck in an office from 9 to 5 for the next fifty years o your life.",
    userId: 2,
  },
  {
    id: 30,
    title: "Things aren't going well at all",
    body: "Things aren't going well at all with mom today. She is just a limp noodle and wants to sleep all the time. I sure hope that things get better soon.",
    userId: 2,
  },
  {
    id: 32,
    title: 'He swung back the fishing pole and cast the line',
    body: 'He swung back the fishing pole and cast the line which ell 25 feet away into the river. The lure landed in the perfect spot and he was sure he would soon get a bite. He never expected that the bite would come from behind in the form of a bear.',
    userId: 2,
  },
  {
    id: 83,
    title: 'Are you getting my texts???',
    body: "\"Are you getting my texts???\" she texted to him. He glanced at it and chuckled under his breath. Of course he was getting them, but if he wasn't getting them, how would he ever be able to answer? He put the phone down and continued on his project. He was ignoring her texts and he planned to continue to do so.",
    userId: 2,
  },
  {
    id: 58,
    title: 'Balloons are pretty and come in different colors',
    body: "Balloons are pretty and come in different colors, different shapes, different sizes, and they can even adjust sizes as needed. But don't make them too big or they might just pop, and then bye-bye balloon. It'll be gone and lost for the rest of mankind. They can serve a variety of purposes, from decorating to water balloon wars. You just have to use your head to think a little bit about what to do with them.",
    userId: 3,
  },
  {
    id: 94,
    title: 'Happiness was different in childhood.',
    body: 'so much then a matter simply of accumulation, of taking things – new experiences, new emotions – and applying them like so many polished tiles to what would someday be the marvellously finished pavilion of the self.',
    userId: 3,
  },
  {
    id: 116,
    title: 'Imagine the silence now, in that place which',
    body: 'is no-place, that anteroom to God where each hour is ten thousand years long. Once you imagined the souls held in a great net, a web spun by God,',
    userId: 3,
  },
  {
    id: 141,
    title: 'A judgment that is necessarily hampered',
    body: 'A judgment that is necessarily hampered, bot only by the scope and limits of his imagination, but by the ever-changing measure of his doubt and self-esteem.',
    userId: 3,
  },
  {
    id: 62,
    title: 'He watched as the young man tried',
    body: 'He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence.',
    userId: 4,
  },
  {
    id: 92,
    title: '‘My dear Bounderby,’ Mr. Gradgrind began',
    body: '‘Now, you’ll excuse me,’ said Bounderby, ‘but I don’t want to be too dear.  That, to start with.  When I begin to be dear to a man, I generally find that his intention is to come over me.',
    userId: 4,
  },
  {
    id: 128,
    title: 'Lyrical poetry is a realm in which any',
    body: 'statement immediately becomes truth. Yesterday the poet said life is a vale of tears; today he said life is a land of smiles; and he was right both times. There is no inconsistency.',
    userId: 4,
  },
  {
    id: 146,
    title: 'Christ, he thinks, by my age I ought to know',
    body: 'You don’t get on by being original. You don’t get on by being bright. You don’t get on by being strong. You get on by being a subtle crook;',
    userId: 4,
  },
  {
    id: 147,
    title: 'They look so fine, and young',
    body: 'They look so fine, and young, and wrapped up in each other. Love is so fresh and clean at that age. Don’t you think?',
    userId: 4,
  },
  {
    id: 17,
    title: 'She was in a hurry.',
    body: "She was in a hurry. Not the standard hurry when you're in a rush to get someplace, but a frantic hurry. The type of hurry where a few seconds could mean life or death. She raced down the road ignoring speed limits and weaving between cars. She was only a few minutes away when traffic came to a dead standstill on the road ahead.",
    userId: 5,
  },
  {
    id: 44,
    title: 'A long black shadow slid across the pavement',
    body: 'A long black shadow slid across the pavement near their feet and the five Venusians, very much startled, looked overhead. They were barely in time to see the huge gray form of the carnivore before it vanished behind a sign atop a nearby building which bore the mystifying information "Pepsi-Cola."',
    userId: 5,
  },
  {
    id: 75,
    title: 'There was something beautiful in his hate.',
    body: "There was something beautiful in his hate. It wasn't the hate itself as it was a disgusting display of racism and intolerance. It was what propelled the hate and the fact that although he had this hate, he didn't understand where it came from. It was at that moment that she realized that there was hope in changing him.",
    userId: 5,
  },
  {
    id: 89,
    title: 'On Saturday nights I would sit by the phone',
    body: 'in the lobby, waiting for Naoko to call. Most of the others were out, so the lobby was usually deserted. I would stare at the grains of light suspended in that silent space, struggling to see into my own heart. What did I want? ',
    userId: 6,
  },
  {
    id: 107,
    title: 'She would never know, because he would',
    body: 'never tell her. Somehow if she’d known the worst parts, she couldn’t have gone on being a haven for him. He was groping for an idea that he couldn’t quite grasp.',
    userId: 6,
  },
  {
    id: 120,
    title: 'When a woman withdraws to give birth the',
    body: 'sun may be shining but the shutters of her room are closed so she can make her own weather. She is kept in the dark so she can dream. Her dreams drift her far away,',
    userId: 6,
  },
  {
    id: 42,
    title: 'You know that tingly feeling you get on the back of your neck sometimes?',
    body: "You know that tingly feeling you get on the back of your neck sometimes? I just got that feeling when talking with her. You know I don't believe in sixth senses, but there is something not right with her. I don't know how I know, but I just do.",
    userId: 7,
  },
  {
    id: 125,
    title: 'Looking back on those incidents,',
    body: 'always appalled by the memory of his passivity, hard though it was to see what else he could have done. He could have refused to pay for the gravy damage to his room, could have refused to change his shoes,',
    userId: 7,
  },
  {
    id: 102,
    title: 'Being in high school, Miles had no idea there',
    body: 'were girls in the world who might be nice to some boy who’d suffered the misfortune of falling in love with them, even when they couldn’t return the favor.',
    userId: 8,
  },
  {
    id: 121,
    title: 'Revolution and youth are closely allied.',
    body: 'can a revolution promise to adults? To some it brings disgrace, to others favor. But even that favor is questionable,',
    userId: 8,
  },
  {
    id: 133,
    title: 'He thought of the cost exacted',
    body: 'He thought of the cost exacted, year after year, by the soil; and it remained as it had been—a little more barren, perhaps, a little more frugal of increase. Nothing had changed. Their lives had been expended in cheerless labor, their wills broken, their intelligences numbed.',
    userId: 8,
  },
  {
    id: 1,
    title: 'His mother had always taught him',
    body: "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him. But the stupidity of the group of people he was talking to made him change his mind.",
    userId: 9,
  },
  {
    id: 52,
    title: "The headache wouldn't go away.",
    body: "The headache wouldn't go away. She's taken medicine but even that didn't help. The monstrous throbbing in her head continued. She had this happen to her only once before in her life and she realized that only one thing could be happening.",
    userId: 9,
  },
  {
    id: 63,
    title: "Many people say that life isn't like a bed of roses.",
    body: "Many people say that life isn't like a bed of roses. I beg to differ. I think that life is quite like a bed of roses. Just like life, a bed of roses looks pretty on the outside, but when you're in it, you find that it is nothing but thorns and pain. I myself have been pricked quite badly.",
    userId: 9,
  },
  {
    id: 115,
    title: 'In the days to follow the hacendado would',
    body: 'come up to the corral where they’d shaped the manada and he and John Grady would walk among the mares and John Grady would argue their points and the hacendado would muse and walk away a fixed distance.',
    userId: 9,
  },
  {
    id: 143,
    title: 'Everything failed to subdue me',
    body: 'Everything failed to subdue me. Soon everything seemed dull: another sunrise, the lives of heroes, failing love, war, the discoveries people made about each other.',
    userId: 9,
  },
  {
    id: 82,
    title: 'Pink ponies and purple giraffes roamed the field.',
    body: 'Pink ponies and purple giraffes roamed the field. Cotton candy grew from the ground as a chocolate river meandered off to the side. What looked like stones in the pasture were actually rock candy. Everything in her dream seemed to be perfect except for the fact that she had no mouth.',
    userId: 10,
  },
  {
    id: 47,
    title: 'The shoes had been there for as long as anyone could remember.',
    body: "The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place. Why nobody had removed them was a question that had been asked time and again, but while they all thought it, nobody had ever found the energy to actually do it.",
    userId: 11,
  },
  {
    id: 4,
    title: 'All he wanted was a candy bar.',
    body: "All he wanted was a candy bar. It didn't seem like a difficult request to comprehend, but the clerk remained frozen and didn't seem to want to honor the request. It might have had something to do with the gun pointed at his face.",
    userId: 12,
  },
  {
    id: 7,
    title: 'This is important to remember.',
    body: "This is important to remember. Love isn't like pie. You don't need to divide it among all your friends and loved ones. No matter how much love you give, you can always give more. It doesn't run out, so don't try to hold back giving it as if it may one day run out. Give it freely and as much as you want.",
    userId: 12,
  },
  {
    id: 45,
    title: 'The red line moved across the page.',
    body: 'The red line moved across the page. With each millimeter it advanced forward, something changed in the room. The actual change taking place was difficult to perceive, but the change was real. The red line continued relentlessly across the page and the room would never be the same.',
    userId: 12,
  },
];
